### ISSUE TITLE
honeypot deployment checklist

### ISSUE THREAD

**Issue by ryanfleming23** [ryanfleming23/honeypot-group-1a#6]
- [x] apply the provided baseline firewall rulesLinks to an external site.
- [x] apply any additional firewall rules you're including
- [x] test to ensure that your data collection is correctly recording the data that you wish to collect
- [x] test to ensure that you to randomize the IP assignment to the type of honeypot to avoid distribution biases (if applicable to your research design, more than likely it will).
- [x] test to ensure that your public IP address matches that of your configured external IP address
- [x] test to ensure that only 1 attacker is on the system (if applicable to your research design, more than likely it will). MITM auto-access does not do this for you (i.e. if 2 different attackers around the world may both sign in as root:root, auto-access allows the first, then the second has a valid cred, so they sign in too).
- [x] test to ensure that your honeypot containers will automatically restart after a full reboot of your host
- [x] test to ensure that your baseline firewall rules (and any additional rules) will be automatically re-applied after a full reboot of your host
- [x] test to ensure that your honeypot IP addresses are reconfigured and the interface re-enabled after a full reboot of your host
- [x] test to ensure that your honeypot data collection are still working correctly after a full reboot of your host
- [x] test to ensure that your recycling script will properly recycle all your containers at least 3 times (many bugs start showing up after 1 or 2 recycles)
- [x] test to ensure that your recycling script will properly reset your MITM (if you're using MITM) and auto-access policies
